# Generated by Django 5.0.1 on 2024-01-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=200, verbose_name='古诗词名称')),
                ('content_age', models.CharField(default='未知', max_length=200, verbose_name='古诗词朝代')),
                ('content_author', models.CharField(default='未知', max_length=200, verbose_name='古诗词作者')),
                ('content_txt', models.TextField(max_length=20000, verbose_name='古诗词内容')),
            ],
            options={
                'verbose_name': '古诗词库',
                'verbose_name_plural': '古诗词库',
            },
        ),
        migrations.CreateModel(
            name='dication_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='默写任务', max_length=200, verbose_name='默写任务')),
                ('task_start_time', models.DateTimeField(verbose_name='任务开始时间')),
                ('task_end_time', models.DateTimeField(verbose_name='任务结束时间')),
            ],
            options={
                'verbose_name': '默写任务',
                'verbose_name_plural': '默写任务',
            },
        ),
    ]
