# Generated by Django 5.0.1 on 2024-01-06 06:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=200, verbose_name='古诗词名称')),
                ('content_age', models.CharField(default='未知', max_length=200, verbose_name='古诗词朝代')),
                ('content_author', models.CharField(default='未知', max_length=200, verbose_name='古诗词作者')),
                ('content_txt', models.TextField(max_length=20000, verbose_name='古诗词内容')),
            ],
            options={
                'verbose_name': '古诗词库',
                'verbose_name_plural': '古诗词库',
            },
        ),
        migrations.CreateModel(
            name='dictation_task_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='默写任务', max_length=200, verbose_name='默写任务名称')),
                ('task_pub_time', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 6, 9, 19, 23831, tzinfo=datetime.timezone.utc), verbose_name='任务发布时间')),
                ('task_start_time', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 6, 9, 19, 23831, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间')),
                ('task_end_time', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 7, 9, 19, 23831, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间')),
                ('status', models.CharField(default='未开始', max_length=200, verbose_name='状态')),
                ('contents', models.ManyToManyField(to='dictation.content', verbose_name='古诗词库')),
                ('groups', models.ManyToManyField(blank=True, to='auth.group', verbose_name='指定班级')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='指定学生')),
            ],
            options={
                'verbose_name': '默写任务-教师端',
                'verbose_name_plural': '默写任务-教师端',
            },
        ),
        migrations.CreateModel(
            name='dictation_task_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='默写任务', max_length=200, verbose_name='默写任务名称')),
                ('task_start_time', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 6, 9, 19, 25867, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间')),
                ('task_end_time', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 7, 9, 19, 25867, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间')),
                ('status', models.CharField(default='未开始', max_length=200, verbose_name='状态')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('contents', models.ManyToManyField(to='dictation.content', verbose_name='古诗词库')),
                ('task_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictation.dictation_task_teacher', verbose_name='任务ID')),
            ],
            options={
                'verbose_name': '默写任务-学生端',
                'verbose_name_plural': '默写任务-学生端',
            },
        ),
    ]
