# Generated by Django 5.0.1 on 2024-01-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0002_delete_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_name', models.CharField(max_length=200, verbose_name='古诗词名称')),
                ('content_age', models.CharField(default='未知', max_length=200, verbose_name='古诗词朝代')),
                ('content_author', models.CharField(default='未知', max_length=200, verbose_name='古诗词作者')),
                ('content_txt', models.TextField(max_length=20000, verbose_name='古诗词内容')),
            ],
            options={
                'verbose_name': '古诗词库',
                'verbose_name_plural': '古诗词库',
            },
        ),
    ]
