# Generated by Django 5.0.1 on 2024-01-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0003_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='dication_task',
            name='contents',
            field=models.ManyToManyField(to='dictation.content', verbose_name='古诗词库'),
        ),
    ]
