# Generated by Django 5.0.1 on 2024-01-06 06:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0004_alter_dictation_task_student_task_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation_task_student',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='学生'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dictation_task_student',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 7, 33, 34, 629363, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_student',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 6, 33, 34, 629363, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 7, 33, 34, 627368, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_pub_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 6, 33, 34, 627368, tzinfo=datetime.timezone.utc), verbose_name='任务发布时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 6, 33, 34, 627368, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间'),
        ),
    ]
