# Generated by Django 5.0.1 on 2024-01-04 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0004_dication_task_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='dication_task',
            name='task_pub_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='任务发布时间'),
            preserve_default=False,
        ),
    ]
