# Generated by Django 5.0.1 on 2024-01-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0005_dication_task_task_pub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='dication_task',
            name='status',
            field=models.CharField(default='未开始', max_length=200, verbose_name='状态'),
        ),
    ]
