# Generated by Django 5.0.1 on 2024-01-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dictation', '0006_dication_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='dictation_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='默写任务', max_length=200, verbose_name='默写任务')),
                ('task_pub_time', models.DateTimeField(auto_now_add=True, verbose_name='任务发布时间')),
                ('task_start_time', models.DateTimeField(verbose_name='任务开始时间')),
                ('task_end_time', models.DateTimeField(verbose_name='任务结束时间')),
                ('status', models.CharField(default='未开始', max_length=200, verbose_name='状态')),
                ('contents', models.ManyToManyField(to='dictation.content', verbose_name='古诗词库')),
                ('group', models.ManyToManyField(to='auth.group', verbose_name='指定组')),
            ],
            options={
                'verbose_name': '默写任务',
                'verbose_name_plural': '默写任务',
            },
        ),
        migrations.DeleteModel(
            name='dication_task',
        ),
    ]
