# Generated by Django 5.0.1 on 2024-01-05 18:01

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dictation', '0008_dictation_task_student_dictation_task_teacher_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictation_task_student',
            options={'verbose_name': '默写任务-学生端', 'verbose_name_plural': '默写任务-学生端'},
        ),
        migrations.AlterModelOptions(
            name='dictation_task_teacher',
            options={'verbose_name': '默写任务-教师端', 'verbose_name_plural': '默写任务-教师端'},
        ),
        migrations.AddField(
            model_name='dictation_task_student',
            name='score',
            field=models.IntegerField(default=None, verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='指定班级'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 19, 1, 54, 611902, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_name',
            field=models.CharField(default='默写任务', max_length=200, verbose_name='默写任务名称'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_pub_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 18, 1, 54, 611902, tzinfo=datetime.timezone.utc), verbose_name='任务发布时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 18, 1, 54, 611902, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='指定学生'),
        ),
    ]
