# Generated by Django 5.0.1 on 2024-01-05 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0009_alter_dictation_task_student_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictation_task_teacher',
            old_name='group',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='dictation_task_teacher',
            old_name='user',
            new_name='users',
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 19, 16, 13, 524927, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_pub_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 18, 16, 13, 524927, tzinfo=datetime.timezone.utc), verbose_name='任务发布时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 18, 16, 13, 524927, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间'),
        ),
    ]
