# Generated by Django 5.0.1 on 2024-01-05 19:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0011_dictation_task_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation_task_student',
            name='task_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictation.dictation_task_teacher'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 20, 7, 12, 234178, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_pub_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 19, 7, 12, 234178, tzinfo=datetime.timezone.utc), verbose_name='任务发布时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 19, 7, 12, 234178, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间'),
        ),
    ]
