# Generated by Django 5.0.1 on 2024-01-06 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0013_alter_dictation_task_student_task_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation_task_student',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 7, 41, 53, 505898, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_student',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 6, 41, 53, 505898, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 7, 41, 53, 503863, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_pub_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 6, 41, 53, 503863, tzinfo=datetime.timezone.utc), verbose_name='任务发布时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 6, 41, 53, 503863, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间'),
        ),
    ]
