# Generated by Django 5.0.1 on 2024-01-05 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0014_alter_dictation_task_teacher_task_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200, verbose_name='测试名称')),
            ],
            options={
                'verbose_name': '测试',
                'verbose_name_plural': '测试',
            },
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 20, 17, 1, 250532, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_pub_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 19, 17, 1, 249519, tzinfo=datetime.timezone.utc), verbose_name='任务发布时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 19, 17, 1, 250532, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间'),
        ),
    ]
