# Generated by Django 5.0.1 on 2024-01-06 18:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0016_alter_dictation_task_student_task_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupname', models.CharField(default='未知', max_length=200, verbose_name='班级名称')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.RemoveField(
            model_name='dictation_task_teacher',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='dictation_task_teacher',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='dictation_task_teacher',
            name='users',
        ),
        migrations.AlterField(
            model_name='content',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='学生姓名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('Class', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dictation.class', verbose_name='班级ID')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='task_teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(default='默写任务', max_length=200, verbose_name='默写任务名称')),
                ('task_pub_time', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 20, 30, 901017, tzinfo=datetime.timezone.utc), verbose_name='任务发布时间')),
                ('task_start_time', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 20, 30, 901017, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间')),
                ('task_end_time', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 19, 20, 30, 901017, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间')),
                ('status', models.CharField(default='未开始', max_length=200, verbose_name='状态')),
                ('classes', models.ManyToManyField(blank=True, to='dictation.class', verbose_name='指定班级')),
                ('contents', models.ManyToManyField(to='dictation.content', verbose_name='古诗词库')),
                ('students', models.ManyToManyField(blank=True, to='dictation.student', verbose_name='指定学生')),
            ],
            options={
                'verbose_name': '默写任务-教师端',
                'verbose_name_plural': '默写任务-教师端',
            },
        ),
        migrations.CreateModel(
            name='task_student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(default='默写任务', max_length=200, verbose_name='默写任务名称')),
                ('task_start_time', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 20, 30, 903048, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间')),
                ('task_end_time', models.DateTimeField(default=datetime.datetime(2024, 1, 6, 19, 20, 30, 903048, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间')),
                ('status', models.CharField(default='未开始', max_length=200, verbose_name='状态')),
                ('score', models.IntegerField(default=0, verbose_name='得分')),
                ('contents', models.ManyToManyField(to='dictation.content', verbose_name='古诗词库')),
                ('student', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dictation.student', verbose_name='学生ID')),
                ('task_teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dictation.task_teacher', verbose_name='任务ID')),
            ],
            options={
                'verbose_name': '默写任务-学生端',
                'verbose_name_plural': '默写任务-学生端',
            },
        ),
        migrations.DeleteModel(
            name='dictation_task_student',
        ),
        migrations.DeleteModel(
            name='dictation_task_teacher',
        ),
    ]
