# Generated by Django 5.0.1 on 2024-01-06 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0017_class_remove_dictation_task_teacher_contents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_student',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 19, 23, 34, 75513, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='task_student',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 23, 34, 75513, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间'),
        ),
        migrations.AlterField(
            model_name='task_teacher',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 19, 23, 34, 72520, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='task_teacher',
            name='task_pub_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 23, 34, 72520, tzinfo=datetime.timezone.utc), verbose_name='任务发布时间'),
        ),
        migrations.AlterField(
            model_name='task_teacher',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 23, 34, 72520, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间'),
        ),
    ]
