# Generated by Django 5.0.1 on 2024-01-06 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0018_alter_task_student_task_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='groupname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.AlterField(
            model_name='task_student',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 19, 25, 21, 392173, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='task_student',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 25, 21, 392173, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间'),
        ),
        migrations.AlterField(
            model_name='task_teacher',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 19, 25, 21, 390179, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='task_teacher',
            name='task_pub_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 25, 21, 390179, tzinfo=datetime.timezone.utc), verbose_name='任务发布时间'),
        ),
        migrations.AlterField(
            model_name='task_teacher',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 25, 21, 390179, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间'),
        ),
    ]
