# Generated by Django 5.0.1 on 2024-01-05 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictation', '0029_remove_dictation_task_student_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation_task_student',
            name='score',
            field=models.IntegerField(default=0, verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 20, 42, 43, 863385, tzinfo=datetime.timezone.utc), verbose_name='任务结束时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_pub_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 19, 42, 43, 863385, tzinfo=datetime.timezone.utc), verbose_name='任务发布时间'),
        ),
        migrations.AlterField(
            model_name='dictation_task_teacher',
            name='task_start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 5, 19, 42, 43, 863385, tzinfo=datetime.timezone.utc), verbose_name='任务开始时间'),
        ),
    ]
